"""init

Revision ID: 6dcfe88834b3
Revises: 
Create Date: 2025-07-28 11:14:05.554005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dcfe88834b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esercizi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('immagine', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('cognome', sa.String(length=50), nullable=False),
    sa.Column('indirizzo', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('abbonamento_inizio', sa.Date(), nullable=True),
    sa.Column('abbonamento_fine', sa.Date(), nullable=True),
    sa.Column('ruolo', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('supervisors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schede',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('validita_inizio', sa.Date(), nullable=True),
    sa.Column('validita_fine', sa.Date(), nullable=True),
    sa.Column('descrizione', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheda_esercizi',
    sa.Column('scheda_id', sa.Integer(), nullable=True),
    sa.Column('esercizio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['esercizio_id'], ['esercizi.id'], ),
    sa.ForeignKeyConstraint(['scheda_id'], ['schede.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheda_esercizi')
    op.drop_table('schede')
    op.drop_table('trainers')
    op.drop_table('supervisors')
    op.drop_table('users')
    op.drop_table('esercizi')
    # ### end Alembic commands ###
