"""Rimozione modelli e risorse non necessari

Revision ID: 864d33222bfd
Revises: 73a77cbd892b
Create Date: 2025-07-24 14:17:11.438684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864d33222bfd'
down_revision = '73a77cbd892b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.drop_table('stores')
    op.drop_table('tags')
    op.drop_table('items_tags')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('cognome', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('indirizzo', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('abbonamento_inizio', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('abbonamento_fine', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('ruolo', sa.String(length=20), nullable=False))
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_column('ruolo')
        batch_op.drop_column('abbonamento_fine')
        batch_op.drop_column('abbonamento_inizio')
        batch_op.drop_column('indirizzo')
        batch_op.drop_column('cognome')
        batch_op.drop_column('nome')

    op.create_table('items_tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=True),
    sa.Column('tag_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('store_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('store_id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
